---
title: "Syndrome Tracker"
format:
  dashboard:
    theme:
      - default
      - custom.scss
server: shiny
---

```{r message=FALSE}
#| context: setup

library(tidyverse)
library(highcharter)
# library(sf)
# library(leaflet)
# library(kcData)

source("scripts/fn.R")

syn <- readRDS("data/syndromes.rds")
ts <- readRDS("data/timeseries.rds")
```

# {.sidebar width=300px}

```{r}
selectInput(
  inputId = "syn",
  label = "Syndrome",
  choices = syn,
  multiple = TRUE,
  selected = syn[[1]][1]
)

# pickerInput(
#   inputId = "syn",
#   label = "Syndrome",
#   choices = syn,
#   multiple = TRUE,
#   selected = syn[1],
#   pickerOptions(
#     actionsBox = TRUE,
#     liveSearch = TRUE,
#     maxOptions = 5
#   )
# )

dateRangeInput(
  inputId = "date",
  label = "Date range",
  start = max(ts$date) - 7,
  end = max(ts$date),
  min = min(ts$date),
  max = max(ts$date)
)

checkboxInput(
  inputId = "alert",
  label = "Show ESSENCE alerts",
  value = TRUE
)
```

# Plot

```{r}
# plotOutput("plot")
highchartOutput("plot")
```

```{r}
#| context: server

tsrctv <- reactive({
  req(input$syn, input$date)
  
  vsyn <- unlist(strsplit(input$syn, ";"))
  
  ts |>
    filter(
      syndrome %in% vsyn,
      date >= input$date[1],
      date <= input$date[2]
    )
})

# output$plot <- renderPlot({
output$plot <- renderHighchart({
  req(tsrctv())
  
  if (input$alert) {
    p <- syn_highchart(tsrctv(), alert = TRUE)
  } else {
    p <- syn_highchart(tsrctv(), alert = FALSE)
  }

  p
})
```


